[package]
name = "flight_controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pid_controller = {git = "https://github.com/JustinEnlow/pid_controller"} # {path = "../pid_controller"}
clamp = {git = "https://github.com/JustinEnlow/clamp"}
inertial_measurement = {path = "../inertial_measurement"}
dimension3 = {git = "https://github.com/JustinEnlow/dimension3"}
# propulsion_control = {git = "https://github.com/JustinEnlow/propulsion_control"}